### ISSUE TITLE
Shortcuts change

### ISSUE THREAD

**Issue by olivierov** [skycc86/npp_binhex_plugin#3]
Hello,
Thank you for your great plugin.

1. '_Ctrl+Shift+Right_' and '_Ctrl+Shift+Left_' are standard key combinations for **word  selection** everywhere and in NPP of course. Replacing these standard selection shortcuts by BinHex's _hex_shift_ functionalities is source of confusion and gives unexpected results.
&ensp;
May I suggest to release this standard shortcuts by the use of the '>' and '<' keys combined with the 'Ctrl' and 'Alt' modifiers for _hex_shift_ / _hex_rotate_ BinHex's functions? I propose the use of these keys for the 2 following reasons:
    - They are well accessible by a lot of keyboard layouts (https://en.wikipedia.org/wiki/Keyboard_layout). But as they are accessible either directly or by using the 'Shift' modifier key, please **don't use the 'Shift' modifier**!
    - They remind the '>>' / '<<' binary shift instructions used in many programming language :wink:
<ol>
It will give these shortcuts:
<ul>
<li>hex_shift >>&ensp;&ensp;&ensp;&ensp;Ctrl+></li>
<li>hex_shift <<&ensp;&ensp;&ensp;&ensp;Ctrl+<</li>
<li>hex_rotate >>&ensp;&ensp;&ensp;Alt+></li>
<li>hex_rotate <<&ensp;&ensp;&ensp;Alt+<</li>
</ul>
</ol>

2. Could you please also add a BinHex's 'Enable' / 'Disable' option (BinHex's plugins menu, toolbar icon)?

3. Adding icons for BinHex's functions in the toolbar will also give direct access to these functions to users...

Thank you for your work.
BR

**Comment by skycc86** [comment]
Hello

let me try to answer your concern below
1. 'Ctrl+Shift+Right' and 'Ctrl+Shift+Left' is the default shortcut key i set during the plugin development. Though user can change this anytime to their preference. The shortcut key can be change as below
    - goto Settings -> Shortcut Mapper
    - then click on Plugin commands tab on top, then you will see list of plugin and its correspond function and shortcut key
    - look for binhex.dll, just click on the shortcut key you wish to change then save it

with this, i think its quite convenience for user to change to their preference anytime :)

2. Did you mean to totally disable whole plugin features ? don't see why we need this, can you elaborate more ?

3. i think all the function should be easily accessible with shortcut key, i can consider to add a single icon which will bringup the list of available functions as an alternative to  menu plugins->binhex

**Comment by olivierov** [comment]
Hello Skycc86,
Thank you for your fast answer.

1. I know that NPP allows us to change the its own shortcut, but I didn't know that it also allows to change the plugin's shortcuts... but IMO, its not a good idea to keep the standard word selection shortcuts as BinHex ones by default.
2. When you are in the Shortcut Mapper window, in all tabs, you can see a lot of conflicts (red lines) between elements like main menu, plugins, ...
Then, I would like to disable plugins when I'm not using it, avoiding shortcut conflicts. E.g, when I'm writing HTML code, I don't need BinHex, JSON, XML, ... plugins and all their shortcuts.
3. Shortcuts are nice, but as I'm an 'old' man, my brain has memory leak an there are too much shortcuts to memorize 😉. An icon in the toolbar may help me to give me direct access to the BinHex functions.

All of these points are only suggestions to improve the user experience.
I thank you again for your plugin which helps me to do my work faster and better.

**Comment by skycc86** [comment]
thanks for the feedback, i will put that into my consideration, it can be consolidate into next release with other improvements :)

**Comment by guy038** [comment]
Hello **Skycc86**,

Many **thanks** for your **new** plugin. Could you have a **glance** to my post, on the **N++ Community** site :

https://notepad-plus-plus.org/community/topic/15860/my-notepad-binhex-plugin/11

As **Olivierov**, I do think that, using the **`Ctrl + Shift + Left`** and **`Ctrl + Shift + Right`** shortcuts, as **default**, isn't a **sensible** solution !

Best Regards,

guy038

**Comment by skycc86** [comment]
issued fixed on release v2.0.0.1,
in v2.0.0.1, all shortcut that ptentially clash with npp default already being remove
user shall configure their own preference shortcut key from the shortcut mapper
