### ISSUE TITLE
Update in NotePad++ DONT work.

### ISSUE THREAD

**Issue by boubou** [skycc86/npp_binhex_plugin#4]
*I use the very latest version of NotePad++ Plugin Manager*
I start NotePad++.
A window pop-up, I click "Update Selected".
The update happens, I restart NotePad++, I went to Plugin Manager > Updates and BinHex is showing as now updated.
Why ?
Could you fix it please ?
I am available to reproduce the issue if you want!

**Comment by skycc86** [comment]
i have fix the issue, please try to update 1 more time, click yes when seeing fail to validate integrity of binhex.dll, this might need some update from the plugin manager side, i have asking the owner to fix this

**Comment by skycc86** [comment]
validate integrity part already fixed also, all should be working now :)

**Comment by skycc86** [comment]
issue fixed
